--°DESAFIO : lISTE O NOME, SOBRENOME E DEPARTAMENTO DE TODOS OS FUNCIONÁRIOS DA TABELA DimEmployee.
--EXIBINDO OS TÍTULOS DAS COLUNAS COMO 'NOME','SOBRENOME' E 'DEPARTAMENTO'.

USE ContosoRetailDW
	
	SELECT FirstName,
			LastName,
			DepartmentName
		FROM DimEmployee
